### PR TITLE
Instance Mode

### PR DESCRIPTION
**Pull request by campionfellin**
Hey!

I was in need of p5.grain for instance mode (wanted to render like 100 of my sketches at once on a page).

So, wrote this, hope you like it! Still seems to work with global mode.

Mostly all is the same except removing global shim, so probably a breaking change for anyone using it.

### CODE REVIEW

**Comment by meezwhite** [comment]
Hi there!

Thanks for your contribution! Having instance mode would definitely be awesome to have.

Since I would also like to implement JS module syntax, so required functions can be imported like so:

```js
import { granulateChannels, tinkerPixels } from 'p5.grain';
```

I'll have to check how instance mode pertains to the module syntax.

Kinda busy atm but I'll have a look as soon as I can and I'm definitely considering this.

**Comment by campionfellin** [comment]
Sounds great! I needed it for myself, so built it, but figured would be useful for you. Feel free to take into the library at your own pace!

**Comment by meezwhite** [comment]
@campionfellin I finally had a chance to have a look at this and it looks great overall! Just fixed two small bugs.

However, having instance mode this way would complicate a little bit the syntax for offscreen graphic buffers:

Previous syntax:
```js
pg.granulateSimple(42);
```
New syntax:
```js
p5grain.granulateSimple(42, false, pg);
```

Previous syntax:
```js
pg.tinkerPixels((index, total) => {
   // ...
});
```
New syntax:
```js
p5grain.tinkerPixels((index, total) => {
    // ...
}, true, pg); // <-- shouldUpdate = true
```

All arguments have to be specified, since `pg` is the last argument.

That's why I've made some changes which makes instance mode possible and keeps the previous syntax, by keeping the code where p5grain methods were registered on `p5.prototype` and on `p5.Graphics.prototype`.

And instead of using `instanceMode` and `instanceRef` there is now one `instance` property. If it's set, then "instance mode is enabled".

I was also wondering whether a single pre-initialized `p5grain` instance, that can be used on multiple `p5` instances, might suffice. 🤔

I've pushed the changes on this repositorie's **campionfellin/main** branch. Could you please pull and check whether this solution works for your use case? It it works for you, let's merge it to your fork's main branch, then I can merge it here.

I'm here, if you have any question and thanks again for your time and for implementing this!

I guess I'll be preparing a contributors section next 🤭

**Comment by campionfellin** [comment]
Hey hey! @meezwhite sorry I have not got a chance to try this yet. I ended up with a different route (not using instance mode anymore). Feel free to merge!

**Pull request merged**
